// Auto-generated frontend configuration
// DO NOT EDIT - Generated by setup script

window.__BACKEND_URL__ = 'http://localhost:8000';
window.__API_BASE__ = 'http://localhost:8000/api/v1';

console.log('🔗 Backend configured:', window.__BACKEND_URL__);
